name: Build Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/setup-go@v4
        with:
          go-version: 'latest'
      - uses: actions/checkout@v3

      - uses: ko-build/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: explabs/mimic
      - run: ko build ./cmd/mimic/main.go --platform=linux/amd64,linux/arm64 --bare -t ${{ github.ref_name }}